# Generated by Django 5.2.3 on 2025-06-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
